### PR TITLE
Fix Travis-CI builds

### PR DESCRIPTION
**Pull request by MSF-Jarvis**

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
Let's see if we even need a second commit

**Comment by MSF-Jarvis** [comment]
:smirk: knew that was the problem, have had this many, many times.

**Comment by afollestad** [comment]
Thanks!

**Comment by MSF-Jarvis** [comment]
That's the least I can do to say thanks!

P.S. are you aware Nock Nock doesn't care whether I actually have my
internet up? It said my sites were down but I wasn't even connected to the
internet... Needs a bug tracker issue?

**Comment by afollestad** [comment]
@MSF-Jarvis I've made some changes for internet connectivity checks, sites will stay in the *"Waiting"* status until internet connectivity returns.

I will need to test it when I'm done with work before I push an update to Google Play

**Comment by MSF-Jarvis** [comment]
Nice, let me know if you need testers, I've got multiple types of sites to
check it against (standard HTTPS, API endpoint, proxied NodeBB forum).

On Aug 2, 2016 2:34 AM, "Aidan Follestad" <notifications@github.com> wrote:

@MSF-Jarvis <https://github.com/MSF-Jarvis> I've made some changes for
internet connectivity checks, sites will stay in the *"Waiting"* status
until internet connectivity returns.

I will need to test it when I'm done with work before I push an update to
Google Play

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/afollestad/nock-nock/pull/1#issuecomment-236707385>,
or mute
the thread

**Comment by CodingFrieda** [comment]
Can you please re-check [Travis](https://travis-ci.org/afollestad/nock-nock) @MSF-Jarvis?

**Comment by MSF-Jarvis** [comment]
It's broken code from what a cursory glance suggests @CodingFreida

**Pull request merged**
